/* This file is still a Redux slice, like appPreferences, but now it handles async data loading
The file controls state.services.  Unlike appPreferences this slice does not just store a selected
value. It stores the state of a request:

Before request:
items = []
isLoading = false
errorMessage = ""

Request started:
items = []
isLoading = true
errorMessage = ""

Request succeeded:
items = service list
isLoading = false
errorMessage = ""

Request failed:
items = old/current value
isLoading = false
errorMessage = "some error"
*/ 

/* createAsyncThunk creates an async Redux action flow. It automatically creates three action states:
pending    -> request started
fulfilled  -> request succeeded
rejected   -> request failed
 */
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";

import type { ServiceListItem } from "../../mock-api/data";
import ClinicServicesService from "../../services/services";

// State Type
interface ServicesState {
  items: ServiceListItem[];
  isLoading: boolean;
  errorMessage: string;
}

const initialState: ServicesState = {
  items: [],              // state.services.items = []
  isLoading: false,       // state.services.isLoading = false
  errorMessage: "",       // state.services.errorMessage = ""
};

/* A thunk is an action that can contain async logic.
Normal Redux action:  
    dispatch(setSelectedCity("brest"));  (This is immediate and synchronous.)
Thunk action:
    dispatch(fetchServices());
This starts an async operation:

Dispatch fetchServices
        |
        v
Redux emits pending action
        |
        v
Call ClinicServicesService.getServices()
        |
        |-- if success -> Redux emits fulfilled action
        |
        |-- if error   -> Redux emits rejected action
*/
export const fetchServices = createAsyncThunk(
  /* "services/fetchServices" is the action type prefix. Redux Toolkit uses it to generate:
  services/fetchServices/pending
  services/fetchServices/fulfilled
  services/fetchServices/rejected
 */
  "services/fetchServices",
  
  /* What is _? The first argument is the argument passed to the thunk. 
  Example if we had:
    dispatch(fetchServices("diagnostics"));
  then _ would be "diagnostics". But here fetchServices() takes no argument, so we use _ to mean:
  'this argument exists, but we do not use it' 

    What is rejectWithValue? 
  return rejectWithValue(error.message);
  This lets us control what becomes action.payload in the rejected case.
 */
  async (_, { rejectWithValue }) => {
    try {
      return await ClinicServicesService.getServices();
    } catch (error) {
      if (error instanceof Error) {
        return rejectWithValue(error.message);
      }

      return rejectWithValue("Failed to load services.");
    }
  },
);


// createSlice
const servicesSlice = createSlice({
  name: "services",
  initialState,
  reducers: {}, // there are no normal synchronous reducers here
  extraReducers: (builder) => {  // extraReducers handles actions generated by createAsyncThunk
    builder
      .addCase(fetchServices.pending, (state) => {
        state.isLoading = true;
        state.errorMessage = "";
      })
      .addCase(fetchServices.fulfilled, (state, action) => {
        state.isLoading = false;
        state.items = action.payload;
      })
      .addCase(fetchServices.rejected, (state, action) => {
        state.isLoading = false;
        state.errorMessage =
          typeof action.payload === "string" ? action.payload : "Failed to load services.";
      });
  },
});

export default servicesSlice.reducer;


/* Full Flow:
ServicesPage mounts
        |
        v
dispatch(fetchServices())
        |
        v
fetchServices.pending
        |
        v
state.services.isLoading = true
        |
        v
ClinicServicesService.getServices()
        |
        | success
        v
fetchServices.fulfilled
        |
        v
state.services.items = action.payload
state.services.isLoading = false

        OR

        | error
        v
fetchServices.rejected
        |
        v
state.services.errorMessage = action.payload
state.services.isLoading = false


Main Difference From appPreferences
appPreferences:
  User action -> dispatch normal action -> state changes immediately
services:
  Page loads -> dispatch async thunk -> pending -> API call -> fulfilled/rejected
*/
